export const FETCH_PAINTINGS = 'FETCH_PAINTINGS';
export const SELECT_ACTIVE_PAINTING = 'SELECT_ACTIVE_PAINTING';
export const DELETE_PAINTING = 'DELETE_PAINTING';
export const UPDATE_FILTER = 'UPDATE_FILTER';
